name = "ubiquity-os-command-start-stop"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.dev]
[env.prod]

[observability]
enabled = true

[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"
