name: Deno Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Configuration and Build"]
    types:
      - completed

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ (github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main') && 'main' || 'development' }}
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install CLI
        run: deno install -gArf jsr:@deno/deployctl

      - name: Prepare Environment Variables
        run: |
          branch_name=$(echo '${{ github.event.workflow_run.head_branch || github.ref }}' | sed 's#refs/heads/##')
          project_name="${{ github.event.repository.name }}"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
          echo "IS_MAIN_BRANCH=${{ (github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main') && 'true' || 'false' }}" >> $GITHUB_ENV

      - name: Generate .env File
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BOT_USER_ID: ${{ secrets.BOT_USER_ID }}
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cat > generate-env.ts <<'EOF'
          const envVars = Deno.env.toObject();
          const filtered = Object.entries(envVars)
            .filter(([k]) => !/^(GITHUB_|RUNNER_|CI|HOME|PATH|PWD|SHELL|USER|LANG|LC_|TZ|DENO_)/.test(k))
            .reduce((acc, [k,v]) => ({...acc, [k]:v}), {});
          await Deno.writeTextFile(".env", 
            Object.entries(filtered)
              .map(([k,v]) => `${k}="${v.replace(/"/g, '\\"')}"`)
              .join("\n")
          );
          EOF
          deno run --allow-env --allow-write=.env generate-env.ts
          rm generate-env.ts

      - name: Manage Deno Deploy Project
        id: deno_project
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          DENO_ORG_ID: ${{ secrets.DENO_ORG_ID }}
        run: |
          deployctl projects create \
            --token=$DENO_DEPLOY_TOKEN \
            --project=$PROJECT_NAME \
            --force \
            --color=never || true

          PROJECT_INFO=$(deployctl projects show --token=$DENO_DEPLOY_TOKEN --project=$PROJECT_NAME --color=never)
          PROJECT_URL=$(echo "$PROJECT_INFO" | grep "Domain(s):" | awk '{print $2}')

          echo "PROJECT_URL=$PROJECT_URL" >> $GITHUB_ENV

      - name: Sync Environment Variables
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deployctl deploy \
            --token=$DENO_DEPLOY_TOKEN \
            --project=$PROJECT_ID \
            --env-file=.env

      - name: Deploy Application
        uses: denoland/deployctl@v1
        id: deno_deploy
        with:
          project: ${{ env.PROJECT_NAME }}
          entrypoint: src/deno.ts
          root: .
          include: "**/*.ts,static/**/*"
          exclude: "**/*.test.ts"

      - name: Generate Deployment URL
        id: deployment_url
        run: |
          if [ "$IS_MAIN_BRANCH" = "true" ]; then
            deployment_url="https://$PROJECT_NAME.deno.dev"
          else
            safe_branch_name=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
            deployment_url="https://$safe_branch_name--$PROJECT_NAME.deno.dev"
          fi
          echo "deployment_url=$deployment_url" >> $GITHUB_OUTPUT
          echo "Deployment URL: $deployment_url"

      - name: Update manifest.json with deployment URL
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const manifestPath = path.resolve("${{ github.workspace }}", './manifest.json');
            const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

            manifest["homepage_url"] = "${{ steps.deployment_url.outputs.deployment_url }}";

            const updatedManifest = JSON.stringify(manifest, null, 2);
            fs.writeFileSync(manifestPath, updatedManifest);
            console.log('Updated manifest:', updatedManifest);

      - name: Get GitHub App token
        if: env.APP_ID != '' && env.APP_PRIVATE_KEY != ''
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.APP_PRIVATE_KEY }}

      - name: Format manifest.json using Deno
        shell: bash
        run: |
          deno fmt --ext=json manifest.json

      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
        with:
          files: |
            manifest.json
          commit-message: "chore: [skip ci] update manifest.json url"
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Write Deployment URL to Summary
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment_url.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
